apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: manager-app-template
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${APP_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: web
      port: 8080
    selector:
      app: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    port:
      targetPort: web
    to:
      kind: Service
      name: ${APP_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - env:
          - name: SCOREBOARD_HOST
            value: ${SCOREBOARD_HOST}
          - name: SCOREBOARD_PORT
            value: ${SCOREBOARD_PORT}
          name: ${APP_NAME}
          image: ruromero/manager-app:3.11
          imagePullPolicy: IfNotPresent
        serviceAccountName: ${APP_NAME}
    triggers:
    - type: ConfigChange
parameters:
- description: Break & Fix Application name
  displayName: Application name
  name: APP_NAME
  required: true
  value: manager-app
- description: Scoreboard application host
  displayName: Scoreboard APP host
  name: SCOREBOARD_HOST
  required: true
- description: Scoreboard application port
  displayName: Scoreboard APP port
  name: SCOREBOARD_PORT
  required: true
