apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: online-oc
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: online-oc
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: online-oc
    name: online-oc
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
      from:
        kind: DockerImage
        name: docker.io/edseymour/gottyforocp:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
    - annotations:
      from:
        kind: DockerImage
        name: docker.io/edseymour/gottyforocp:v3.7
      generation: 2
      importPolicy: {}
      name: v3.7
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: online-oc
    name: online-oc
  spec:
    replicas: 1
    selector:
      app: online-oc
      deploymentconfig: online-oc
    template:
      metadata:
        labels:
          app: online-oc
          deploymentconfig: online-oc
      spec:
        containers:
        - env:
          - name: HOME
            value: /workspace
          image: ''
          imagePullPolicy: Always
          name: online-oc
          ports:
          - containerPort: 8080
            protocol: TCP
        serviceAccountName: online-oc
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - online-oc
        from:
          kind: ImageStreamTag
          name: online-oc:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: online-oc
    name: online-oc
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: online-oc
      deploymentconfig: online-oc
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: online-oc
    name: online-oc
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: online-oc
      weight: 100
    wildcardPolicy: None
